const ActionTypes = {
  movie: {
    LOAD_MOVIES_ERROR: 'LOAD_MOVIES_ERROR',
    MOVIES_ARE_LOADING: 'MOVIES_ARE_LOADING',
    LOAD_MOVIES_SUCCESS: 'LOAD_MOVIES_SUCCESS',
    LOAD_MOVIE_DETAILS_ERROR: 'LOAD_MOVIE_DETAILS_ERROR',
    MOVIE_DETAILS_ARE_LOADING: 'MOVIE_DETAILS_ARE_LOADING',
    LOAD_MOVIE_DETAILS_SUCCESS: 'LOAD_MOVIE_DETAILS_SUCCESS'
  }
};

export default ActionTypes;
